### ISSUE TITLE
build vuejs faild

### ISSUE THREAD

**Issue by jinjin123** [gobeli/django-vue-todolist#1]
npm run build

> django-vue-todolist@ build /root/django-vue-todolist/todolist/static
> cross-env NODE_ENV=production browserify -g envify src/main.js | uglifyjs -c warnings=false -m > dist/build.js

sh: dist/build.js: no such file or directory
Error: Cannot find module '/root/django-vue-todolist/todolist/static/src/main.js' from '/root/django-vue-todolist/todolist/static'
    at /root/django-vue-todolist/todolist/static/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/root/django-vue-todolist/todolist/static/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/root/django-vue-todolist/todolist/static/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /root/django-vue-todolist/todolist/static/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

why that not create  'dist' directory? I  think you missing build.js

**Comment by gobeli** [comment]
Right, thanks for that one. The build script was wrong, is fixed and you should be able to build
